[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
resolver = "2"

members = [
    #libs
    "libs/webscrapping",
    # entry point
    "webserver"
]

[worspace.dependencies]
serde = { version = "1.0.201", features = ["derive"] }
serde_json = { version = "1.0.117" }