@startuml
participant client

client -> runtime : new req arrived
runtime -> middleware : check req and limit them. TODO How do we find out that channel capacity is full?
middleware -> footage_handler : we want to proceed a req

footage_handler -> runtime : spawn for downloading with selenium instance (max 2 for artgrid and artlist)
footage_handler -> runtime : file was downloaded. Run a new task that notify that file is downloaded
footage_handler -> runtime : if file is downloaded server it to user

@enduml
