###
# curl -X POST http://localhost:3000/admin -H "Content-Type: application/json" -H "Authorization: Bearer your_token" -d '{ "name": "ddd", "passwd":"http://"}'

POST http://localhost:3000/admin
Authorization: Bearer your_token
Content-Type: application/json

{ "name": "ddd", "passwd":"http://"}

###
POST http://localhost:3000/footager
Authorization: Bearer your_token
Content-Type: application/json

{ "name": "test", "url": "https://artgrid.io/clip/6243583/snow-winter-chugach-alaska" }